- name: Remove the lock
  file:
    path: "/tmp/qtsingleapp-qBitto-624a-3e5"
    state: absent

- name: Remove the lockfile
  file:
    path: "/tmp/qtsingleapp-qBitto-624a-3e5-lockfile"
    state: absent

- name: Start qBitTorrent instances
  service:
    name: qbittorrent{{ item }}
    state: started
